language: cpp

jobs:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - llvm
    - os: osx
      osx_image: xcode11.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - llvm
      before_install:
        - export LLVM_DIR_DECL_FOR_OSX="-DLLVM_DIR=\"/usr/local/opt/llvm/lib/cmake/llvm\""

script:
  - mkdir build && cd build
  - cmake .. $LLVM_DIR_DECL_FOR_OSX
  - cmake --build . --config release

env:
  global:
    - GH_REF: github.com/yangzh1998/purpo.git
    - P_BRANCH: main
    - U_NAME: yangzh1998
    - U_EMAIL: yangzh1998@hotmail.com